// generated by @ng-toolkit/universal
    const port = process.env.PORT || 8080;
    const project = process.env.npm_config_project;
    const targetServer = project ? `./dist/${project}/server` : `./dist/server`;
    
    const server = require(targetServer);
    
    server.app.listen(port, () => {
        console.log("Listening on: http://localhost:" + port );
    });
    