// generated by @ng-toolkit/universal
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';

@NgModule({
    imports: [
    ]
})
export class AppBrowserModule {}
